### ISSUE TITLE
Support For Apple Manifests & Codesigning

### ISSUE THREAD

**Issue by RoblesJ** [permutive-engineering/permutive-ios-spm#9]
Greetings, as you may be aware starting on May 1st it will be mandatory for 3rd party SDKs to provide within their modules a privacy manifest detailing the reasons why certaing APIs are being used as well as any of the user propperties being used in order to avoid tracking / fingerprinting

As such i have inspected your binaries and found you will need to provide one such privacy manifest due to the following APIs usage.

Analyzing binaries: ./ios-arm64_x86_64-simulator/Permutive_iOS.framework/Permutive_iOS ./ios-arm64_x86_64-maccatalyst/Permutive_iOS.framework/Permutive_iOS ./ios-arm64/Permutive_iOS.framework/Permutive_iOS
---
Used symbols in binary ./ios-arm64_x86_64-simulator/Permutive_iOS.framework/Permutive_iOS: NSUserDefaults
Used symbols in binary ./ios-arm64_x86_64-maccatalyst/Permutive_iOS.framework/Permutive_iOS: NSUserDefaults
Used symbols in binary ./ios-arm64/Permutive_iOS.framework/Permutive_iOS: NSUserDefaults

Also i have noted your xcframework is not codesigned and this is also a requirement stated by apple

Documentation:
https://developer.apple.com/support/third-party-SDK-requirements/
https://developer.apple.com/documentation/bundleresources/privacy_manifest_files
https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api

**Comment by TevJ** [comment]
Hi @RoblesJ,

We've been working to get this out but had some difficulties ensuring the privacy manifest was correctly included when building the target application statically.

The latest release should include the privacy manifest in the bundle which should roll up into you application's privacy manifest.

Please let us know if there are any issues.

Thanks,
Tom

**Comment by RoblesJ** [comment]
Hello, @TevJ thanks for the quick response, as far as i can see the privacy manifests seem to have the basic keys however there are no items inside them 

From the scan i performed i can tell UserDefaults is being used and as such it should be declared
https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api#4278401
for example

<key>NSPrivacyAccessedAPITypes</key>
    <array>
                <dict>
            <key>NSPrivacyAccessedAPIType</key>
            <string>NSPrivacyAccessedAPICategoryUserDefaults</string>
            <key>NSPrivacyAccessedAPITypeReasons</key>
            <array>
                <string>CA92.1</string>
            </array>
        </dict>
    </array>

i suppose the most common would be CA92.1 or 1C8F.1 if your sdk takes data from app groups 

As a note using xcode 15.3 helps a lot when trying to see diferent reasons on privacy manifests

Then on NSPrivacyCollectedDataTypes 
https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_data_use_in_privacy_manifests

if you take any data from the user such as deviceId for analytics for example or tracking then you would have to state so there.

here is an example of google maps privacy manifest
[GoogleMapsPrivacy](https://dl.google.com/geosdk/PrivacyManifests/GoogleMapsPrivacy.bundle.zip?hl=es-419)

Regarding the static framework i have to do some changes to migrate versions in order to attempt to archive your new SDK however apple has also uploaded some notes regarding adding privacy manifests to static frameworks here
https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/adding_a_privacy_manifest_to_your_app_or_third-party_sdk

Thanks for keeping up the good work!

**Comment by TevJ** [comment]
Thanks for the extra info @RoblesJ !

We've just released v2.1.1 with the included information on the UserDefaults usage. We don't track any device IDs for Permutive specific usage so I've left NSPrivacyCollectedDataTypes empty.

We followed that guide to include the manifest and I can see it's included in the .xcframework so it should be picked up by host applications.

**Comment by RoblesJ** [comment]
Hello! thanks for your work.

As far as i can see this should be up to apple's standards now.

If anything else comes up from apple's side i'll come back with feed back though i believe this should be resolved

**Comment by TevJ** [comment]
No problem! Thanks for raising the issue.

I'll mark this issue as closed with #12  but if you face any other problems please feel free to either comment on this issue or open another one and we'll look into it.
